<?php

declare(strict_types=1);

/**
 * @file
 * Provides a students entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function school_theme(): array {
  return [
    'school_students' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for students templates.
 *
 * Default template: school-students.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the students information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_school_students(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for classes templates.
 *
 * Default template: classes.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the classes information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_classes(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

