<?php

/**
 * @file
 * Primary module hooks for payment module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function payment_theme(): array {
  return [
    'school_payment' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for school payment templates.
 *
 * Default template: school-payment.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the school payment information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_school_payment(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

